<div class="<?php Bootstrap::compile('page-title') ?>">
   <h1><?php echo Mage::helper('sales')->__('Returns') ?></h1>
</div>
<div class="<?php Bootstrap::compile('block-content') ?>">
   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="<?php Bootstrap::compile('search-form') ?>" name="guest_post">
       <ul class="<?php Bootstrap::compile('form-alt') ?>">
           <li style="clear:both;">
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:150px;">
                   <label for="oar_order_id" class="<?php Bootstrap::compile('required') ?>"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
               </div>
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:305px;">
                   <input type="text" class="<?php Bootstrap::compile('input-text-required-entry') ?>" id="oar_order_id" name="oar_order_id" style="width:300px;"/>
               </div>
           </li>
           <li style="clear:both;">
               <div class="<?php Bootstrap::compile('input-box') ?>">
                   <?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
                </div>
           </li>
           <li style="clear:both;">
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:150px;">
                   <label for="oar_billing_lastname" class="<?php Bootstrap::compile('required') ?>"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
               </div>
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:305px;">
                   <input type="text" class="<?php Bootstrap::compile('input-text-required-entry') ?>" id="oar_billing_lastname" name="oar_billing_lastname"  style="width:300px;"/>
               </div>
           </li>
           <li style="clear:both;">
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:150px;">
                   <label class="<?php Bootstrap::compile('required') ?>"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
               </div>
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:305px;">
                   <select name="oar_type" id="quick_search_type_id" class="<?php Bootstrap::compile('select-guest-select') ?>" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email">Email Address</option>
                       <option value="zip">ZIP Code</option>
                   </select>
               </div>
           </li>
           <li id="oar-email" style="clear:both;">
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:150px;">
                   <label for="oar_email" class="<?php Bootstrap::compile('required') ?>"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
               </div>
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:305px;">
                   <input type="text" class="<?php Bootstrap::compile('input-text-validate-email-required-entry') ?>" id="oar_email" name="oar_email"  style="width:300px;"/>
               </div>
           </li>
           <li id="oar-zip" style="display:none;clear:both;">
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:150px;">
                   <label for="oar_zip" class="<?php Bootstrap::compile('required') ?>"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
               </div>
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;width:305px;">
                   <input type="text" class="<?php Bootstrap::compile('input-text-required-entry') ?>" id="oar_zip" name="oar_zip" style="width:300px;"/>
               </div>
           </li>
           <li style="clear:both;">
               <div class="<?php Bootstrap::compile('input-box') ?>" style="float:left;text-align:right;width:455px">
                   <button type="submit" title="Continue" class="<?php Bootstrap::compile('button') ?>"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
               </div>
           </li>
       </ul>
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
